In [1]:
import numpy as np

In [2]:
a = np.array([[2,3,4,5], [6,7,8,9]])
print(a)

[[2 3 4 5]
 [6 7 8 9]]


In [7]:
# Selecionando um item na array
# Como selecionar: array[row(linha), col(coluna)]
a[1,-2] #Também funciona lendo a array de frente para trás

7

In [10]:
# Mostrando uma row inteira
a[0,:]

array([2, 3, 4, 5])

In [11]:
# Motrando uma col inteira
a[:,1]

array([3, 7])